<!DOCTYPE TS><TS>
<context>
    <name>@default</name>
    <message>
        <source>ICON_VTKVIEWER_VIEW_GLOBALPAN</source>
        <translation>vtk_view_glpan.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FITAREA</source>
        <translation>vtk_view_fitarea.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FRONT</source>
        <translation>vtk_view_front.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_RESET</source>
        <translation>vtk_view_reset.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_RIGHT</source>
        <translation>vtk_view_right.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_FITALL</source>
        <translation>vtk_view_fitall.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_BOTTOM</source>
        <translation>vtk_view_bottom.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_TOP</source>
        <translation>vtk_view_top.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_PAN</source>
        <translation>vtk_view_pan.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_ROTATE</source>
        <translation>vtk_view_rotate.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_DUMP</source>
        <translation>vtk_view_camera_dump.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_BACK</source>
        <translation>vtk_view_back.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_ZOOM</source>
        <translation>vtk_view_zoom.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_LEFT</source>
        <translation>vtk_view_left.png</translation>
    </message>
    <message>
        <source>ICON_VTKVIEWER_VIEW_TRIHEDRON</source>
        <translation>vtk_view_triedre.png</translation>
    </message>
</context>
</TS>
