<!DOCTYPE TS><TS>
<context>
    <name>@default</name>
    <message>
        <source>ICON_GRADUATED_AXES</source>
        <translation>view_graduated_axes.png</translation>
    </message>
    <message>
        <source>ICON_SVTK_SCALING</source>
        <translation>view_scaling.png</translation>
    </message>
    <message>
        <source>ICON_UPDATE_RATE</source>
        <translation>view_update_rate.png</translation>
    </message>
    <message>
        <source>ICON_PRINT_VIEW</source>
        <translation>view_print.png</translation>
    </message>
</context>
</TS>
